apiVersion: v1
kind: Service
metadata:
  name: luckypanda-rng-service
  namespace: default
  labels:
    app: luckypanda-rng
spec:
  type: ClusterIP
  selector:
    app: luckypanda-rng
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None